# Generated by Django 6.1.1 on 2026-10-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orders_id', models.IntegerField(primary_key=True, serialize=False)),
                ('orders_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
